background: # 既是博客的背景，又是文章默认头图
  path: https://cdn.jsdelivr.net/gh/303snowing/303snowing.github.io@hexo-img/bg.jpeg
avatar: https://cdn.jsdelivr.net/gh/303snowing/303snowing.github.io@hexo-img/head-icon.jpg # 网站 Logo
copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'
iconlib: https://at.alicdn.com/t/font_2492588_6aklf99w93e.css

comment: gitalk
gitalk:
  admin: 303snowing # 管理员 GitHub ID
  owner: 303snowing # 持有该 repo 的 GitHub user
  repo: 303snowing.github.io # 存放评论的 issue 所在的 repo
  clientID: 4a3e8f198a01684edff6 # GitHub Client ID
  clientSecret: b98da32dd0145a9e1e4aad8dc5912b97312895dc # GitHub Client Secret
  createIssueManually: true

mathjax:
  enable: true
  per_page: true # 按需加载mathjax

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能

search: https://cn.bing.com/search?q=site:303snowing.github.io # https://www.google.com/search?q={你的博客链接}

menu:
  回到首页: 
    - /
    - icon-home
  文章归档: 
    - /archives
    - icon-container
  关于博客:
    - /about
    - icon-info-circle
  我的简历:
    - /resume/resume_java.html
    - icon-info-circle

social:
  QQ群: 
    - https://jq.qq.com/?_wv=1027&k=jXaWd3W3
    - icon-QQ
    - rgb(249, 174, 8)
    - rgba(249, 174, 8, .1)
  <img src=https://cdn.jsdelivr.net/gh/303snowing/303snowing.github.io@hexo-img/wechat.png width=100 height=100/>:
  - 
  - icon-wechat-fill
  - rgb(25, 23, 23)
  - rgba(25, 23, 23, .15)
  哔哩哔哩:
    - https://space.bilibili.com/176335655
    - icon-bilibili
    - rgb(231, 106, 141)
    - rgba(231, 106, 141, .15)
  GitHub:
    - https://github.com/303snowing/
    - icon-github
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
  CSDN:
    - http://blog.csdn.net/u012793104?viewmode=list
    - icon-csdn1
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
